"""
Bible Builder — Analysis Pipeline Step 5

Aggregates BeatStates into the three output artefacts:
  - CharacterBible (per character)
  - SceneBible (per scene)
  - WorldBible (per play)

Each bible is generated by an LLM reading the full set of BeatStates
and producing a structured synthesis. The CharacterBible also includes
a tactic distribution (counted from the BeatStates) and few-shot lines
sampled from canonical utterances.
"""
from __future__ import annotations

import json
import logging
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

import anthropic
from config import ANTHROPIC_API_KEY, BIBLES_DIR, get_model
from schemas import (
    Beat, BeatState, CharacterBible, Play, SceneBible, WorldBible,
)

client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
logger = logging.getLogger(__name__)

# ────────────────────────────────────────────────────────────────────────────
# Character Bible
# ────────────────────────────────────────────────────────────────────────────

_CHARACTER_BIBLE_SYSTEM = """\
You are a dramaturg and acting coach synthesizing a comprehensive character analysis.
Given a character's BeatState arc across a play, produce a structured CHARACTER BIBLE.

Return ONLY valid JSON with this structure:
{
  "superobjective": "the character's deepest, play-long want",
  "wounds_fears_needs": "enduring psychological wounds, fears, and unmet needs",
  "recurring_tactics": ["tactic1", "tactic2", ...],
  "preferred_defense_mechanisms": ["defense1", "defense2", ...],
  "psychological_contradictions": ["contradiction1", "contradiction2", ...],
  "speech_style": "description of how they speak (rhythm, vocabulary, rhetorical habits)",
  "rhetorical_patterns": ["pattern1", "pattern2", ...],
  "arc_by_scene": {"act_scene": "what changes in this scene for the character", ...},
  "known_facts": ["fact1", "fact2"],
  "secrets": ["secret1", "secret2"]
}
"""

_CHARACTER_BIBLE_USER = """\
PLAY: {play_title}
CHARACTER: {character}

BEAT-BY-BEAT ARC:
{arc_block}

SAMPLE CANONICAL LINES:
{sample_lines}

Synthesize the CHARACTER BIBLE as JSON.
"""


def _collect_character_arc(character: str, play: Play) -> tuple[list[BeatState], list[str]]:
    """Return (beat_states, sample_lines) for a character across the whole play."""
    beat_states: list[BeatState] = []
    sample_lines: list[str] = []
    for act in play.acts:
        for scene in act.scenes:
            for beat in scene.beats:
                for bs in beat.beat_states:
                    if bs.character == character:
                        beat_states.append(bs)
                # Collect a few lines from this character
                for utt in (u for b in scene.beats for u in b.utterances):
                    if utt.speaker == character and len(utt.text) > 20:
                        sample_lines.append(utt.text)
    # Sample up to 20 lines evenly across the play
    if len(sample_lines) > 20:
        step = len(sample_lines) // 20
        sample_lines = sample_lines[::step][:20]
    return beat_states, sample_lines


def _arc_to_str(beat_states: list[BeatState]) -> str:
    lines = []
    for bs in beat_states:
        lines.append(
            f"{bs.beat_id}: want={bs.desire_state!r} | tactic={bs.tactic_state!r} | "
            f"affect(v={bs.affect_state.valence:.1f},a={bs.affect_state.arousal:.1f}) | "
            f"defense={bs.defense_state!r} | contradiction={bs.psychological_contradiction!r}"
        )
    return "\n".join(lines)


_MAX_ARC_ENTRIES = 30


def _sample_beat_states(beat_states: list[BeatState], max_entries: int = _MAX_ARC_ENTRIES) -> tuple[list[BeatState], bool]:
    """Return (sampled_beat_states, was_sampled).

    Always preserves the first and last entries so arc endpoints are intact.
    Samples evenly across the middle when len > max_entries.
    """
    if len(beat_states) <= max_entries:
        return beat_states, False
    # Always keep first and last; sample the middle
    middle = beat_states[1:-1]
    step = max(1, len(middle) // (max_entries - 2))
    sampled_middle = middle[::step][: max_entries - 2]
    return [beat_states[0]] + sampled_middle + [beat_states[-1]], True


def _parse_json_response(raw: str) -> dict:
    """Strip markdown fences and parse JSON from LLM response."""
    text = raw.strip()
    if text.startswith("```"):
        text = text.split("```")[1].lstrip("json").strip().rstrip("```").strip()
    return json.loads(text)


def build_character_bible(character: str, play: Play) -> CharacterBible:
    """Build a CharacterBible for one character using LLM synthesis."""
    beat_states, sample_lines = _collect_character_arc(character, play)
    if not beat_states:
        return CharacterBible(play_id=play.id, character=character)

    tactic_counts = Counter(bs.tactic_state for bs in beat_states if bs.tactic_state)

    # Sample arc for large characters to avoid overwhelming the LLM
    arc_for_prompt, was_sampled = _sample_beat_states(beat_states)
    arc_block = _arc_to_str(arc_for_prompt)
    if was_sampled:
        arc_block = (
            f"[Note: {len(arc_for_prompt)} of {len(beat_states)} beat_states shown, "
            f"sampled evenly across the arc. First and last are included.]\n" + arc_block
        )

    prompt = _CHARACTER_BIBLE_USER.format(
        play_title=play.title,
        character=character,
        arc_block=arc_block,
        sample_lines="\n".join(f"  - {l}" for l in sample_lines),
    )

    data = _call_and_parse_character_bible(character, prompt, len(beat_states))

    bible = CharacterBible(
        play_id=play.id,
        character=character,
        superobjective=data.get("superobjective", ""),
        wounds_fears_needs=data.get("wounds_fears_needs", ""),
        recurring_tactics=data.get("recurring_tactics", []),
        preferred_defense_mechanisms=data.get("preferred_defense_mechanisms", []),
        psychological_contradictions=data.get("psychological_contradictions", []),
        speech_style=data.get("speech_style", ""),
        rhetorical_patterns=data.get("rhetorical_patterns", []),
        few_shot_lines=sample_lines[:10],
        known_facts=data.get("known_facts", []),
        secrets=data.get("secrets", []),
        arc_by_scene=data.get("arc_by_scene", {}),
        tactic_distribution=dict(tactic_counts),
    )
    return bible


def _call_and_parse_character_bible(character: str, prompt: str, beat_state_count: int) -> dict:
    """Call the LLM and parse JSON, with one retry on failure."""
    response = client.messages.create(
        model=get_model("bible"),
        max_tokens=4096,
        system=_CHARACTER_BIBLE_SYSTEM,
        messages=[{"role": "user", "content": prompt}],
    )
    raw = response.content[0].text

    try:
        return _parse_json_response(raw)
    except json.JSONDecodeError:
        logger.warning(
            "JSON parse failed for character %s (%d beat_states). "
            "Raw response starts with: %.200s",
            character, beat_state_count, raw,
        )

    # Retry once with an explicit JSON-only reminder
    logger.info("Retrying character bible for %s with JSON reminder...", character)
    retry_prompt = (
        prompt + "\n\nIMPORTANT: Your previous response was not valid JSON. "
        "Return ONLY a single JSON object with no commentary, no markdown fences, "
        "and no text before or after the JSON."
    )
    response = client.messages.create(
        model=get_model("bible"),
        max_tokens=4096,
        system=_CHARACTER_BIBLE_SYSTEM,
        messages=[{"role": "user", "content": retry_prompt}],
    )
    raw = response.content[0].text

    try:
        return _parse_json_response(raw)
    except json.JSONDecodeError:
        logger.error(
            "JSON parse failed AGAIN for character %s on retry. "
            "Raw response starts with: %.200s",
            character, raw,
        )
        return {}


# ────────────────────────────────────────────────────────────────────────────
# Scene Bible
# ────────────────────────────────────────────────────────────────────────────

_SCENE_BIBLE_SYSTEM = """\
You are a dramaturg analyzing a single scene. Given the utterances and beat states,
produce a SCENE BIBLE describing the dramatic engine of this scene.

Return ONLY valid JSON:
{
  "dramatic_pressure": "the overall pressure or urgency driving this scene",
  "what_changes": "what concretely changes by the end of this scene",
  "hidden_tensions": "subterranean conflicts not spoken aloud",
  "beat_map": "prose summary of how the beats progress through this scene"
}
"""

_SCENE_BIBLE_USER = """\
PLAY: {play_title} | ACT {act} SCENE {scene}

UTTERANCES:
{utterance_block}

BEAT STATES:
{beat_states_block}

Produce the SCENE BIBLE as JSON.
"""


def build_scene_bible(act_num: int, scene_num: int, play: Play) -> SceneBible:
    """Build a SceneBible for one scene."""
    scene_obj = next(
        (s for a in play.acts if a.number == act_num for s in a.scenes if s.scene == scene_num),
        None,
    )
    if scene_obj is None:
        return SceneBible(play_id=play.id, act=act_num, scene=scene_num)

    utterances = [u for b in scene_obj.beats for u in b.utterances]
    utt_block = "\n".join(f"  {u.speaker}: {u.text}" for u in utterances[:60])

    beat_states_lines = []
    for beat in scene_obj.beats:
        for bs in beat.beat_states:
            beat_states_lines.append(
                f"  Beat {beat.index} | {bs.character}: tactic={bs.tactic_state!r}"
                f" want={bs.desire_state!r}"
            )
    bs_block = "\n".join(beat_states_lines)

    response = client.messages.create(
        model=get_model("bible"),
        max_tokens=1024,
        system=_SCENE_BIBLE_SYSTEM,
        messages=[{"role": "user", "content": _SCENE_BIBLE_USER.format(
            play_title=play.title,
            act=act_num,
            scene=scene_num,
            utterance_block=utt_block,
            beat_states_block=bs_block,
        )}],
    )
    raw = response.content[0].text.strip()
    if raw.startswith("```"):
        raw = raw.split("```")[1].lstrip("json").strip().rstrip("```").strip()
    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        data = {}

    bible = SceneBible(
        play_id=play.id,
        act=act_num,
        scene=scene_num,
        dramatic_pressure=data.get("dramatic_pressure", ""),
        what_changes=data.get("what_changes", ""),
        hidden_tensions=data.get("hidden_tensions", ""),
        beat_map=data.get("beat_map", ""),
    )
    return bible


# ────────────────────────────────────────────────────────────────────────────
# World Bible
# ────────────────────────────────────────────────────────────────────────────

_WORLD_BIBLE_SYSTEM = """\
You are a dramaturg. Given a play's title and author, produce a WORLD BIBLE
describing the given circumstances that constrain all characters.

Return ONLY valid JSON:
{
  "era": "historical period and place",
  "genre": "dramatic genre and tone",
  "social_norms": ["norm1", "norm2", ...],
  "factual_timeline": ["event1 (before play begins)", "event2", ...],
  "genre_constraints": ["constraint1", "constraint2", ...]
}
"""


def build_world_bible(play: Play) -> WorldBible:
    """Build a WorldBible using LLM knowledge of the play."""
    response = client.messages.create(
        model=get_model("world_bible"),
        max_tokens=1024,
        system=_WORLD_BIBLE_SYSTEM,
        messages=[{"role": "user", "content": f"Play: {play.title}\nAuthor: {play.author}"}],
    )
    raw = response.content[0].text.strip()
    if raw.startswith("```"):
        raw = raw.split("```")[1].lstrip("json").strip().rstrip("```").strip()
    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        data = {}

    return WorldBible(
        play_id=play.id,
        era=data.get("era", ""),
        genre=data.get("genre", ""),
        social_norms=data.get("social_norms", []),
        factual_timeline=data.get("factual_timeline", []),
        genre_constraints=data.get("genre_constraints", []),
    )


# ────────────────────────────────────────────────────────────────────────────
# Orchestrator
# ────────────────────────────────────────────────────────────────────────────

def _count_character_beat_states(play: Play) -> dict[str, int]:
    """Count how many beat states each character has across the play."""
    from collections import Counter
    counts: Counter = Counter()
    for act in play.acts:
        for scene in act.scenes:
            for beat in scene.beats:
                for bs in beat.beat_states:
                    counts[bs.character] += 1
    return dict(counts)


def _existing_bible_characters(play: Play) -> set[str]:
    """Return the set of characters that already have bibles."""
    return {cb.character.upper() for cb in play.character_bibles}


def build_all_bibles(
    play: Play,
    characters: list[str] | None = None,
    skip_scene_bibles: bool = False,
    skip_world_bible: bool = False,
    min_beat_states: int = 0,
) -> Play:
    """Build and attach all bibles to the play, then save to disk.

    Args:
        play: The Play object with BeatStates already extracted.
        characters: If provided, build bibles only for these characters.
                    Otherwise build for all characters in the play.
        skip_scene_bibles: If True, skip rebuilding SceneBibles.
        skip_world_bible: If True, skip rebuilding WorldBible.
        min_beat_states: Only build bibles for characters with at least
                         this many beat states. 0 means no threshold.
    """
    print(f"[bible_builder] Building bibles for {play.title}...")

    # World bible
    if not skip_world_bible:
        play.world_bible = build_world_bible(play)
        print("  [+] WorldBible done")
    else:
        print("  [skip] WorldBible (already exists)")

    # Determine target characters, with deduplication
    existing = _existing_bible_characters(play)
    beat_counts = _count_character_beat_states(play)

    if characters:
        target_chars = [c.upper() for c in characters]
    else:
        target_chars = play.characters

    # Filter by min_beat_states
    if min_beat_states > 0:
        target_chars = [c for c in target_chars if beat_counts.get(c, 0) >= min_beat_states]

    # Skip characters that already have bibles
    new_chars = [c for c in target_chars if c.upper() not in existing]
    skipped = len(target_chars) - len(new_chars)
    if skipped > 0:
        print(f"  [skip] {skipped} characters already have bibles")

    for character in new_chars:
        bs_count = beat_counts.get(character, 0)
        print(f"  Building CharacterBible for {character} ({bs_count} beat states)...")
        bible = build_character_bible(character, play)
        play.character_bibles.append(bible)

    # Scene bibles
    if not skip_scene_bibles:
        play.scene_bibles = []  # clear to avoid duplicates on re-run
        for act in play.acts:
            for scene in act.scenes:
                sb = build_scene_bible(act.number, scene.scene, play)
                play.scene_bibles.append(sb)
        print(f"  [+] {len(play.scene_bibles)} SceneBibles done")
    else:
        print(f"  [skip] SceneBibles (already exist: {len(play.scene_bibles)})")

    # Persist
    out_path = BIBLES_DIR / f"{play.id}_bibles.json"
    out_path.write_text(play.model_dump_json(indent=2))
    print(f"[bible_builder] Saved to {out_path}")
    return play
