"""
Bible Builder — Analysis Pipeline Step 5

Aggregates BeatStates into the three output artefacts:
  - CharacterBible (per character)
  - SceneBible (per scene)
  - WorldBible (per play)

Each bible is generated by an LLM reading the full set of BeatStates
and producing a structured synthesis. The CharacterBible also includes
a tactic distribution (counted from the BeatStates) and few-shot lines
sampled from canonical utterances.
"""
from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

import anthropic
from config import ANALYSIS_MODEL, ANTHROPIC_API_KEY, BIBLES_DIR
from schemas import (
    Beat, BeatState, CharacterBible, Play, SceneBible, WorldBible,
)

client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

# ────────────────────────────────────────────────────────────────────────────
# Character Bible
# ────────────────────────────────────────────────────────────────────────────

_CHARACTER_BIBLE_SYSTEM = """\
You are a dramaturg and acting coach synthesizing a comprehensive character analysis.
Given a character's BeatState arc across a play, produce a structured CHARACTER BIBLE.

Return ONLY valid JSON with this structure:
{
  "superobjective": "the character's deepest, play-long want",
  "wounds_fears_needs": "enduring psychological wounds, fears, and unmet needs",
  "recurring_tactics": ["tactic1", "tactic2", ...],
  "preferred_defense_mechanisms": ["defense1", "defense2", ...],
  "psychological_contradictions": ["contradiction1", "contradiction2", ...],
  "speech_style": "description of how they speak (rhythm, vocabulary, rhetorical habits)",
  "rhetorical_patterns": ["pattern1", "pattern2", ...],
  "arc_by_scene": {"act_scene": "what changes in this scene for the character", ...},
  "known_facts": ["fact1", "fact2"],
  "secrets": ["secret1", "secret2"]
}
"""

_CHARACTER_BIBLE_USER = """\
PLAY: {play_title}
CHARACTER: {character}

BEAT-BY-BEAT ARC:
{arc_block}

SAMPLE CANONICAL LINES:
{sample_lines}

Synthesize the CHARACTER BIBLE as JSON.
"""


def _collect_character_arc(character: str, play: Play) -> tuple[list[BeatState], list[str]]:
    """Return (beat_states, sample_lines) for a character across the whole play."""
    beat_states: list[BeatState] = []
    sample_lines: list[str] = []
    for act in play.acts:
        for scene in act.scenes:
            for beat in scene.beats:
                for bs in beat.beat_states:
                    if bs.character == character:
                        beat_states.append(bs)
                # Collect a few lines from this character
                for utt in (u for b in scene.beats for u in b.utterances):
                    if utt.speaker == character and len(utt.text) > 20:
                        sample_lines.append(utt.text)
    # Sample up to 20 lines evenly across the play
    if len(sample_lines) > 20:
        step = len(sample_lines) // 20
        sample_lines = sample_lines[::step][:20]
    return beat_states, sample_lines


def _arc_to_str(beat_states: list[BeatState]) -> str:
    lines = []
    for bs in beat_states:
        lines.append(
            f"{bs.beat_id}: want={bs.desire_state!r} | tactic={bs.tactic_state!r} | "
            f"affect(v={bs.affect_state.valence:.1f},a={bs.affect_state.arousal:.1f}) | "
            f"defense={bs.defense_state!r} | contradiction={bs.psychological_contradiction!r}"
        )
    return "\n".join(lines)


def build_character_bible(character: str, play: Play) -> CharacterBible:
    """Build a CharacterBible for one character using LLM synthesis."""
    beat_states, sample_lines = _collect_character_arc(character, play)
    if not beat_states:
        return CharacterBible(play_id=play.id, character=character)

    tactic_counts = Counter(bs.tactic_state for bs in beat_states if bs.tactic_state)

    prompt = _CHARACTER_BIBLE_USER.format(
        play_title=play.title,
        character=character,
        arc_block=_arc_to_str(beat_states),
        sample_lines="\n".join(f"  - {l}" for l in sample_lines),
    )
    response = client.messages.create(
        model=ANALYSIS_MODEL,
        max_tokens=2048,
        system=_CHARACTER_BIBLE_SYSTEM,
        messages=[{"role": "user", "content": prompt}],
    )
    raw = response.content[0].text.strip()
    if raw.startswith("```"):
        raw = raw.split("```")[1].lstrip("json").strip().rstrip("```").strip()

    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        data = {}

    bible = CharacterBible(
        play_id=play.id,
        character=character,
        superobjective=data.get("superobjective", ""),
        wounds_fears_needs=data.get("wounds_fears_needs", ""),
        recurring_tactics=data.get("recurring_tactics", []),
        preferred_defense_mechanisms=data.get("preferred_defense_mechanisms", []),
        psychological_contradictions=data.get("psychological_contradictions", []),
        speech_style=data.get("speech_style", ""),
        rhetorical_patterns=data.get("rhetorical_patterns", []),
        few_shot_lines=sample_lines[:10],
        known_facts=data.get("known_facts", []),
        secrets=data.get("secrets", []),
        arc_by_scene=data.get("arc_by_scene", {}),
        tactic_distribution=dict(tactic_counts),
    )
    return bible


# ────────────────────────────────────────────────────────────────────────────
# Scene Bible
# ────────────────────────────────────────────────────────────────────────────

_SCENE_BIBLE_SYSTEM = """\
You are a dramaturg analyzing a single scene. Given the utterances and beat states,
produce a SCENE BIBLE describing the dramatic engine of this scene.

Return ONLY valid JSON:
{
  "dramatic_pressure": "the overall pressure or urgency driving this scene",
  "what_changes": "what concretely changes by the end of this scene",
  "hidden_tensions": "subterranean conflicts not spoken aloud",
  "beat_map": "prose summary of how the beats progress through this scene"
}
"""

_SCENE_BIBLE_USER = """\
PLAY: {play_title} | ACT {act} SCENE {scene}

UTTERANCES:
{utterance_block}

BEAT STATES:
{beat_states_block}

Produce the SCENE BIBLE as JSON.
"""


def build_scene_bible(act_num: int, scene_num: int, play: Play) -> SceneBible:
    """Build a SceneBible for one scene."""
    scene_obj = next(
        (s for a in play.acts if a.number == act_num for s in a.scenes if s.scene == scene_num),
        None,
    )
    if scene_obj is None:
        return SceneBible(play_id=play.id, act=act_num, scene=scene_num)

    utterances = [u for b in scene_obj.beats for u in b.utterances]
    utt_block = "\n".join(f"  {u.speaker}: {u.text}" for u in utterances[:60])

    beat_states_lines = []
    for beat in scene_obj.beats:
        for bs in beat.beat_states:
            beat_states_lines.append(
                f"  Beat {beat.index} | {bs.character}: tactic={bs.tactic_state!r}"
                f" want={bs.desire_state!r}"
            )
    bs_block = "\n".join(beat_states_lines)

    response = client.messages.create(
        model=ANALYSIS_MODEL,
        max_tokens=1024,
        system=_SCENE_BIBLE_SYSTEM,
        messages=[{"role": "user", "content": _SCENE_BIBLE_USER.format(
            play_title=play.title,
            act=act_num,
            scene=scene_num,
            utterance_block=utt_block,
            beat_states_block=bs_block,
        )}],
    )
    raw = response.content[0].text.strip()
    if raw.startswith("```"):
        raw = raw.split("```")[1].lstrip("json").strip().rstrip("```").strip()
    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        data = {}

    bible = SceneBible(
        play_id=play.id,
        act=act_num,
        scene=scene_num,
        dramatic_pressure=data.get("dramatic_pressure", ""),
        what_changes=data.get("what_changes", ""),
        hidden_tensions=data.get("hidden_tensions", ""),
        beat_map=data.get("beat_map", ""),
    )
    return bible


# ────────────────────────────────────────────────────────────────────────────
# World Bible
# ────────────────────────────────────────────────────────────────────────────

_WORLD_BIBLE_SYSTEM = """\
You are a dramaturg. Given a play's title and author, produce a WORLD BIBLE
describing the given circumstances that constrain all characters.

Return ONLY valid JSON:
{
  "era": "historical period and place",
  "genre": "dramatic genre and tone",
  "social_norms": ["norm1", "norm2", ...],
  "factual_timeline": ["event1 (before play begins)", "event2", ...],
  "genre_constraints": ["constraint1", "constraint2", ...]
}
"""


def build_world_bible(play: Play) -> WorldBible:
    """Build a WorldBible using LLM knowledge of the play."""
    response = client.messages.create(
        model=ANALYSIS_MODEL,
        max_tokens=1024,
        system=_WORLD_BIBLE_SYSTEM,
        messages=[{"role": "user", "content": f"Play: {play.title}\nAuthor: {play.author}"}],
    )
    raw = response.content[0].text.strip()
    if raw.startswith("```"):
        raw = raw.split("```")[1].lstrip("json").strip().rstrip("```").strip()
    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        data = {}

    return WorldBible(
        play_id=play.id,
        era=data.get("era", ""),
        genre=data.get("genre", ""),
        social_norms=data.get("social_norms", []),
        factual_timeline=data.get("factual_timeline", []),
        genre_constraints=data.get("genre_constraints", []),
    )


# ────────────────────────────────────────────────────────────────────────────
# Orchestrator
# ────────────────────────────────────────────────────────────────────────────

def build_all_bibles(play: Play, characters: list[str] | None = None) -> Play:
    """Build and attach all bibles to the play, then save to disk."""
    print(f"[bible_builder] Building bibles for {play.title}...")

    # World bible
    play.world_bible = build_world_bible(play)
    print("  [+] WorldBible done")

    # Character bibles
    target_chars = characters or play.characters
    for character in target_chars:
        print(f"  Building CharacterBible for {character}...")
        bible = build_character_bible(character, play)
        play.character_bibles.append(bible)

    # Scene bibles
    for act in play.acts:
        for scene in act.scenes:
            sb = build_scene_bible(act.number, scene.scene, play)
            play.scene_bibles.append(sb)
    print(f"  [+] {len(play.scene_bibles)} SceneBibles done")

    # Persist
    out_path = BIBLES_DIR / f"{play.id}_bibles.json"
    out_path.write_text(play.model_dump_json(indent=2))
    print(f"[bible_builder] Saved to {out_path}")
    return play
